### ISSUE TITLE
hacktoberfest

### ISSUE THREAD

**Issue by ssurbhi09** [ssurbhi09/Table._.project#1]
Add well description of table project in readme section.

**Comment by shivi2912** [comment]
Mam I would like to work on this project too...I am new to github...please assign me.

**Comment by ssurbhi09** [comment]
Yes u can go ahead!

**Comment by shivi2912** [comment]
I have done it but it doesn't contain haktoberfest tag... :/ 
Can you add that ??

**Comment by ssurbhi09** [comment]
It alredy has hacktoberfest tag

**Comment by ssurbhi09** [comment]
U didn't send pr?

**Comment by ssurbhi09** [comment]
![Screenshot_20211006-194926](https://user-images.githubusercontent.com/79759981/136221595-d397aa8d-ffc7-4e38-844e-d21b95b99082.jpg)
See it contain  @shivi2912

**Comment by ssurbhi09** [comment]
Now u see

**Comment by shivi2912** [comment]
still it doesn't contain
@ssurbhi09  last one thing.
 
![shivii](https://user-images.githubusercontent.com/91618828/136274525-50f714e4-230a-4316-bf9c-e3a21cc6c3d5.png)

Go to about> In the Topic > add Hacktoberfest

**Comment by ssurbhi09** [comment]
Done
